### ISSUE TITLE
Link missing - 404 error

### ISSUE THREAD

**Issue by vunhan** [djmaze/docker-appimage-recipe-builder#1]
While build Spotify, I got 404 error on this

`wget -c http://ftp.us.debian.org/debian/pool/main/g/gconf/top`

Can you please recheck this link, thank you!

**Comment by djmaze** [comment]
I experienced this too. This seems to be an intermittent problem. Just try running the build again!

**Comment by vunhan** [comment]
Okay, it works now. Thank you @djmaze
